
from django.conf.urls import url

from mobilecheckin.views import login, appointments, overview
from mobilecheckin.views import checkin , walkin , html2canvasproxy


urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', appointments.index, name='index'),     
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', login.loginview, name='login'),   
    url(r'^login/$', login.loginview, name='login'),
    url(r'^logout/$', login.logoutview, name='logout'),
    url(r'^request/$', login.requestview, name='request'),
    url(r'^password/change$', login.passchange, name='passchange'),
    url(r'^password/create$', login.passcreate, name='passcreate'),
    url(r'^password/reset$', login.passreset, name='passreset'),
    url(r'^username/reset$', login.userreset, name='userreset'),
    url(r'^firstlogin/$', login.firstlogin, name='firstlogin'),
    url(r'^terms/$', login.terms, name='terms'),
    url(r'^overview/$', overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/meters$', overview.meters_ajax_view, name='meters'),
    url(r'^overview/searchcustomer$',overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/row$', overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),   
    url(r'^overview/daily/status$', overview.status_ajax_view, name='ov_daily_status'),
     url(r'^overview/daily/status/slab$', overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/appointment/detail$', overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^appoinment/update$', appointments.appointment_update, name='appointment_update'),
    url(r'^appoinment/removeservice$', appointments.remove_service, name='remove_service'),
    url(r'^checkin/(?P<appointment_id>\d+)/$', checkin.index, name='checkin'), 
    url(r'^checkin/odometer/(?P<appointment_id>\d+)/$', checkin.get_odo, name='get_odo'),
    url(r'^checkin/servicerepair/(?P<appointment_id>\d+)/$', checkin.get_serviceandrepair, name='get_service_repair'),
    url(r'^checkin/getreview/(?P<appointment_id>\d+)/$', checkin.get_reviewandsign, name='get_review'),
    url(r'^checkin/getodohistory/(?P<appointment_id>\d+)/$', checkin.get_odometer_history, name='get_odo_history'),
    url(r'^checkin/savevin/(?P<appointment_id>\d+)/$', checkin.save_vin, name='save_vin'),
    url(r'^checkin/getservicerepair$', checkin.get_service_repair_list, name='get_service_repair_list'), 
    url(r'^checkin/addservicerepair/(?P<appointment_id>\d+)/$', checkin.add_service_repair, name='add_service_repair'),
    url(r'^checkin/removeservicerepair/(?P<appointment_id>\d+)/$', checkin.remove_service_repair, name='remove_service_repair'),
    url(r'^checkin/getbynameservicerepair$', checkin.get_by_name_service_repair, name='get_by_name_service_repair'), 
    url(r'^checkin/getwalkaround/(?P<appointment_id>\d+)/$', checkin.get_walkaround, name='get_walkaround'),
    url(r'^checkin/addwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.add_notes_walkaround, name='add_walkaround_notes'),
    url(r'^checkin/getwalkaroundmedia/(?P<appointment_id>\d+)/$', checkin.get_walkaround_media, name='get_walkaround_media'),
    url(r'^checkin/getwalkaroundnotes/(?P<appointment_id>\d+)/$', checkin.get_walkaround_notes, name='get_walkaround_notes'),
    url(r'^checkin/getselectedvehicledetails$', checkin.get_selected_vehicle, name='get_selected_vehicle'), 
    url(r'^checkin/addinitials/(?P<appointment_id>\d+)/$', checkin.add_walkaround_initials, name='add_initials'),
    url(r'^checkin/acceptappointment/(?P<appointment_id>\d+)/$', checkin.accept_appointment_summary, name='accept_appointment'),
    url(r'^checkin/cancelappointment/(?P<appointment_id>\d+)/$', checkin.cancle_appointment_summary, name='cancel_appointment'),
    url(r'^walkinappointmet/$', walkin.create_appointment, name='walkin_appointment'),
    url(r'^walkinsearchcustomer/$', walkin.searchuser, name='walkin_search'),
    url(r'^image_proxy/$', html2canvasproxy.imgProxy, name='image_proxy'),
    url(r'^checkin/getselectedvehiclemap$', checkin.get_selected_vehicle_map, name='get_selected_vehicle_map'), 
    url(r'^checkin/get_tire_thread/(?P<appointment_id>\d+)/$', checkin.get_tire_thread, name='get_tire_thread'),
    url(r'^checkin/add_appointment_notes/(?P<appointment_id>\d+)/$', checkin.add_tire_notes, name='add_tire_notes'),
]