
from django.conf.urls import url

from dealership import views

import views.login
import views.chat
from views.overview import *
from views.appointment import *
from views.customers import *
from views.rservices import *
from views.manage import *

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^$', views.login.index, name='index'),      
     url(r'delete_models', views.manage.delete_models, name='delete_models'),
    url(r'create_models', views.manage.create_models, name='create_models'),
    url(r'^login/(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.loginview, name='login'),  
    url(r'^login/$', views.login.loginview, name='login'),
    url(r'^logout/$', views.login.logoutview, name='logout'),
    url(r'^request/$', views.login.requestview, name='request'),
    url(r'^password/change$', views.login.passchange, name='passchange'),
    url(r'^password/create$', views.login.passcreate, name='passcreate'),
    url(r'^password/reset$', views.login.passreset, name='passreset'),
    url(r'^username/reset$', views.login.userreset, name='userreset'),
    url(r'^terms/$', views.login.terms, name='terms'),
    url(r'^firstlogin/$', views.login.firstlogin, name='firstlogin'),
    #chat
    url(r'^chats/$', views.chat.chats, name='chats'),
    url(r'^chat/$', views.chat.chat, name='chat'),
    #overview
    url(r'^overview/$', views.overview.overview, name='overview'),    
    #url(r'^overview/time/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    url(r'^overview/daily$', views.overview.ov_time_daily, name='ov_time_daily'),
    #url(r'^overview/advisor/daily$', views.overview.ov_adv_daily, name='ov_adv_daily'),
    #url(r'^overview/status/daily$', views.overview.ov_status_daily, name='ov_status_daily'),
    #url(r'^overview/time/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    url(r'^overview/weekly$', views.overview.ov_time_weekly, name='ov_time_weekly'),
    #url(r'^overview/advisor/weekly$', views.overview.ov_adv_weekly, name='ov_adv_weekly'),
    #url(r'^overview/status/weekly$', views.overview.ov_status_weekly, name='ov_status_weekly'),
    #overview_ajax
    url(r'^overview/wallboard$', views.overview.wallboard_ajax_view, name='wallboard'),
    url(r'^overview/searchcustomer$', views.overview.searchcustomer_ajax_view, name='searchcustomer'),
    url(r'^overview/time/daily/slab$', views.overview.dailyapt_ajax_view, name='ov_time_daily_slab'),
    url(r'^overview/time/daily/search$', views.overview.time_daily_search_ajax_view, name='ov_time_daily_search'),
    url(r'^overview/time/daily/appt$', views.overview.time_daily_search_appt_ajax_view, name='ov_time_daily_search_appt'),
    url(r'^overview/time/daily/row$', views.overview.appointment_row_ajax_view, name='ov_time_daily_row'),
    url(r'^overview/time/weekly/day$', views.overview.time_weekly_day_ajax_view, name='ov_time_weekly_day'),
    url(r'^overview/time/weekly/slab$', views.overview.time_weekly_slab_ajax_view, name='ov_time_weekly_slab'),
    url(r'^overview/daily/advisor$', views.overview.advisor_ajax_view, name='ov_daily_advisor'),
    url(r'^overview/daily/advisor/slab$', views.overview.advisor_daily_slab_ajax_view, name='ov_advisor_daily_slab'),
    url(r'^overview/weekly/advisor/slab$', views.overview.advisor_weekly_slab_ajax_view, name='ov_advisor_weekly_slab'),   
    url(r'^overview/daily/status$', views.overview.status_ajax_view, name='ov_daily_status'),
    url(r'^overview/daily/wayaway$', views.overview.wayaway_ajax_view, name='ov_daily_wayaway'),
    url(r'^overview/daily/status/slab$', views.overview.status_daily_slab_ajax_view, name='ov_status_daily_slab'),
    url(r'^overview/weekly/status/slab$', views.overview.status_weekly_slab_ajax_view, name='ov_status_weekly_slab'),
    url(r'^overview/appointment/detail$', views.overview.appointment_detail_ajax_view, name='ov_appointment_detail'),
    url(r'^overview/update/creaditcard$', views.overview.appointment_update_creditcard, name='ov_update_cc'),
    url(r'^overview/update/vehicle$', views.overview.appointment_update_vehicle, name='ov_update_vehicle'),
    url(r'^overview/update/insurance$', views.overview.appointment_update_insurance, name='ov_update_insurance'),
    #appointment
    url(r'^appointment/$', views.appointment.appointment, name='appointment'),  
    url(r'^appointment/create/update', views.appointment.appointment_create_update, name='appointment_create_update'), 
    url(r'^appointment/customer$', views.appointment.appointment_customer_ajax_view, name='appointment_customer'), 
    url(r'^appointment/customer/vehicle/delete$', views.appointment.customer_delete_vehicle_ajax_view, name='appointment_customer_vehicle_delete'),
    url(r'^appointment/update/time$', views.appointment.appointment_time_ajax_view, name='appointment_update_time'), 
    url(r'^appointment/wayaway$', views.appointment.appointment_wayaway_ajax_view, name='appointment_wayaway'), 
    url(r'^appointment/wayaway/save$', views.appointment.appointment_wayaway_save_ajax, name='appointment_wayaway_save'),
    url(r'^appointment/repair$', views.appointment.appointment_repair_ajax_view, name='appointment_repair'), 
    url(r'^appointment/accountinfo$', views.appointment.appointment_account_info_ajax_view, name='appointment_accountinfo'),
    url(r'^appointment/book', views.appointment.appointment_book_ajax_view, name='appointment_book'),
    url(r'^appointment/remove/service', views.appointment.appointment_remove_service, name='appointment_remove_service'),
    
    #customers
    url(r'^customers/$', views.customers.customers, name='customers'),  
    url(r'^customers/add/user$', views.customers.save_customer_ajax, name='customers_add_user'),
    url(r'^customers/add/vehicle$', views.customers.save_vehicle_ajax, name='customers_add_vehicle'),
    url(r'^customers/add/appointment$', views.customers.save_appointment_ajax, name='customers_add_appointment'),
    url(r'^customers/add/reminder', views.customers.save_guest_reminder_ajax, name='customers_add_reminder'),    
    #repair and servicea
    url(r'^rservices/$', views.rservices.rservices, name='rservices'),
    url(r'^rservices/form$', views.rservices.get_rservices_form, name='rservices_form'),
    url(r'^rservices/create/update', views.rservices.rservices_create_update, name='rservices_create_update'),  
    url(r'^rservices/delete', views.rservices.rservices_delete, name='rservices_delete'),  
    #dealership_manage
    url(r'^manage/$', views.manage.manage, name='manage'),
    url(r'^manage/deatil$', views.manage.details, name='manage_details'),
    url(r'^manage/user_term_advisor$', views.manage.add_user_advisor, name='add_user_advisor'),
    url(r'^manage/add_amenities$', views.manage.add_amenities, name='add_amenities'),
    url(r'^manage/delete_amenities$', views.manage.delete_amenities, name='delete_amenities'),
    url(r'^manage/get_resource_link$', views.manage.get_resource_link, name='get_resource_link'),
    url(r'^manage/add_resource_link$', views.manage.add_resource_link, name='add_resource_link'),
    url(r'^manage/delete_resource_link$', views.manage.delete_resource_link, name='delete_resource_link'),
    url(r'^manage/update_resource_link$', views.manage.update_resource_link, name='update_resource_link'),
    url(r'^manage/get_shopcontacts$', views.manage.get_shopcontacts, name='get_shopcontacts'),
    url(r'^manage/add_shopcontacts$', views.manage.add_shopcontacts, name='add_shopcontacts'),
    url(r'^manage/delete_shopcontacts$', views.manage.delete_shopcontacts, name='delete_shopcontacts'),
    url(r'^manage/update_shopcontacts$', views.manage.update_shopcontacts, name='update_shopcontacts'),
    url(r'^manage/get_marketing$', views.manage.get_marketing, name='get_marketing'),
    url(r'^manage/add_marketing$', views.manage.add_marketing, name='add_marketing'),
    url(r'^manage/get_feedback$', views.manage.get_feedback, name='get_feedback'),
    url(r'^manage/add_feedback$', views.manage.add_feedback, name='add_feedback'),
    url(r'^manage/get_serviceemail$', views.manage.get_serviceemail, name='get_serviceemail'),
    url(r'^manage/add_serviceemail$', views.manage.add_serviceemail, name='add_serviceemail'),
    url(r'^manage/delete_email$', views.manage.delete_email, name='delete_email'),
    url(r'^manage/update_email$', views.manage.update_email, name='update_email'),
    url(r'^manage/get_sms$', views.manage.get_sms, name='get_sms'),
    url(r'^manage/add_sms$', views.manage.add_sms, name='add_sms'),
    url(r'^manage/delete_sms$', views.manage.delete_sms, name='delete_sms'),
    url(r'^manage/update_sms$', views.manage.update_sms, name='update_sms'),
    url(r'^manage/get_shphr$', views.manage.get_shophrs, name='get_shophrs'),
    url(r'^manage/add_shphr$', views.manage.add_shophrs, name='add_shophrs'),
    url(r'^manage/delete_shphr$', views.manage.delete_shophrs, name='delete_shophrs'),
    url(r'^manage/update_shphr$', views.manage.update_shophrs, name='update_shophrs'),
    url(r'^manage/get_holidays$', views.manage.get_holidays, name='get_holidays'),
    url(r'^manage/add_holiday$', views.manage.add_holiday, name='add_holiday'),
    url(r'^manage/delete_holiday$', views.manage.delete_holiday, name='delete_holiday'),
    url(r'^manage/update_holiday$', views.manage.update_holiday, name='update_holiday'),
    url(r'^manage/get_uaform$', views.manage.get_user_advisor_form, name='get_uaform'),
    url(r'^manage/get_editviewuaform$', views.manage.get_edit_view_useradvisor, name='get_editviewuaform'),
    url(r'^manage/edituaform$', views.manage.edit_user_advisor, name='edituaform'),
    url(r'^manage/addteam$', views.manage.add_team, name='add_team'),
    url(r'^manage/editteam$', views.manage.edit_team, name='edit_team'),
    url(r'^manage/addmembers$', views.manage.add_members_team, name='add_team_members'),
    url(r'^manage/deletemembers$', views.manage.delete_members_team, name='delete_team_members'),
    url(r'^manage/removeteam$', views.manage.remove_team, name='remove_team'),
    url(r'^manage/removeuseradvisor$', views.manage.remove_user_advisor, name='remove_user_advisor'),
    url(r'^manage/all_favorites', views.manage.get_ajax_all_favorites, name='all_favorites'),
    url(r'^manage/dealer_favorites', views.manage.get_ajax_dealer_favorites, name='dealer_favorites'),
    url(r'^manage/save_dealer_favorites', views.manage.save_ajax_dealer_favorites, name='save_dealer_favorites'),
    url(r'^manage/add_package', views.manage.add_package, name='add_package'),
    url(r'^manage/add_category', views.manage.add_category, name='add_category'),
    url(r'^manage/get_category', views.manage.get_category, name='get_category'),
    url(r'^manage/get_inspection_items', views.manage.get_inspection_items, name='get_insp_items'),
    url(r'^manage/add_cat_items', views.manage.add_category_inspection_item, name='add_cat_items'),
    url(r'^manage/remove_cat_items', views.manage.remove_category_inspection_item, name='remove_cat_items'),
    url(r'^manage/add_new_item', views.manage.add_new_item, name='add_new_item'),
    url(r'^manage/edit_flag', views.manage.edit_flags, name='edit_flag'),
    url(r'^manage/add_flag', views.manage.add_flags, name='add_flag'),
    url(r'^manage/del_flag', views.manage.del_flags, name='del_flag'),
    url(r'^manage/get_package_detail', views.manage.get_package_detail, name='get_package_detail'),
    url(r'^manage/edit_package', views.manage.edit_package, name='edit_package'),
    url(r'^manage/delete_package', views.manage.delete_package, name='delete_package'),
    url(r'^manage/get_edit_cat', views.manage.get_cat_edit, name='get_edit_cat'),
    url(r'^manage/get_cat', views.manage.edit_cat, name='edit_cat'),
    url(r'^manage/delete_cat', views.manage.delete_cat, name='delete_cat'),
    url(r'^manage/delete_items', views.manage.delete_category_inspection_item, name='delete_items'),
    url(r'^customer/appointmenthistory/(?P<customer_id>\d+)/(?P<vehicle_id>\d+)/$', views.customers.appointment_history, name='appointment_history'),
    url(r'^customer/edit_customer', views.customers.edit_customer, name='edit_customer'),
#     url(r'^(?P<dealer_code>[a-zA-Z0-9_-]+)/?$', views.login.index, name='index'),
]